from modules.telephony.provider import TelephonyProvider
from typing import Optional, Dict, Any
import uuid
import asyncio
import logging

logger = logging.getLogger(__name__)

class MockTelephonyProvider(TelephonyProvider):
    """A mock provider for testing the sales call lifecycle without placing real calls."""

    def __init__(self):
        self.active_calls = {}

    async def create_call(self, to_phone: str, from_phone: str, webhook_url: str, metadata: Optional[Dict[str, Any]] = None) -> str:
        call_id = f"mock_call_{uuid.uuid4().hex}"
        self.active_calls[call_id] = {
            "to": to_phone,
            "from": from_phone,
            "status": "ringing",
            "metadata": metadata
        }
        logger.info(f"[MOCK_TELEPHONY] Calling {to_phone} from {from_phone} (call_id={call_id})")
        
        # Simulate ring and answer in background
        asyncio.create_task(self._simulate_call_lifecycle(call_id, webhook_url))
        
        return call_id

    async def end_call(self, provider_call_id: str) -> bool:
        if provider_call_id in self.active_calls:
            self.active_calls[provider_call_id]["status"] = "completed"
            logger.info(f"[MOCK_TELEPHONY] Call {provider_call_id} ended.")
            return True
        return False

    async def get_call_status(self, provider_call_id: str) -> str:
        call = self.active_calls.get(provider_call_id)
        if call:
            return call["status"]
        return "failed"

    async def _simulate_call_lifecycle(self, call_id: str, webhook_url: str):
        import httpx
        from services import conversation_service
        
        async with httpx.AsyncClient() as client:
            # 1. Ringing
            await asyncio.sleep(1.0)
            if self.active_calls.get(call_id, {}).get("status") != "ringing":
                return
            await client.post(webhook_url, json={"event": "ringing", "provider_call_id": call_id})
                
            # 2. Answered
            await asyncio.sleep(1.0)
            self.active_calls[call_id]["status"] = "in_progress"
            logger.info(f"[MOCK_TELEPHONY] Call {call_id} answered.")
            await client.post(webhook_url, json={"event": "answered", "provider_call_id": call_id})
            
            # 3. Simulate Conversation turns (mock Voice Bridge)
            await asyncio.sleep(1.0)
            
            # We need the conversation ID generated by the answered webhook. We can fetch it by inspecting the db 
            # (only for mock test purposes)
            from core.database import col_sales_calls
            from bson import ObjectId
            
            sales_call_id = self.active_calls[call_id]["metadata"].get("sales_call_id")
            if sales_call_id:
                call_doc = await col_sales_calls().find_one({"_id": ObjectId(sales_call_id)})
                if call_doc and call_doc.get("conversation_id"):
                    cid = call_doc["conversation_id"]
                    com = call_doc["company_id"]
                    
                    # Use the actual AI pipeline via SalesAIOperator
                    from services.sales_ai_orchestrator import SalesAIOperator
                    agent_id = call_doc.get("agent_id")
                    logger.info(f"[SALES_AI_SESSION_STARTED] conversation_id={cid}")
                    
                    # Ensure greeting is present (like in channels_twilio.py)
                    from core.database import col_agents
                    agent = await col_agents().find_one({"_id": ObjectId(agent_id), "company_id": com})
                    lang = agent.get("default_language", "en-IN") if agent else "en-IN"
                    greeting = agent.get("greeting_messages", {}).get(lang, "Hello! How can I help you today?")
                    if "{company_name}" in greeting:
                        # Assuming we have company name, but we can just leave it or try to fetch
                        from core.database import col_companies
                        comp = await col_companies().find_one({"_id": ObjectId(com)})
                        cname = comp.get("name", "Company") if comp else "Company"
                        greeting = greeting.format(company_name=cname)
                    
                    await conversation_service.add_message(com, cid, "assistant", greeting, lang)

                    # Scenario turns from requirements
                    scenarios = [
                        "What is ZeniaHR?",
                        "What is the pricing?",
                        "We need attendance and payroll management for 100 employees.",
                        "What is payroll?"
                    ]
                    
                    for turn_text in scenarios:
                        logger.info(f"[MOCK_TELEPHONY] Processing turn: {turn_text}")
                        # Provide natural delay
                        await asyncio.sleep(0.5)
                        await SalesAIOperator.process_text_turn(com, agent_id, cid, turn_text)
            
            # 4. Completed
            await asyncio.sleep(2.0)
            if self.active_calls.get(call_id, {}).get("status") == "in_progress":
                self.active_calls[call_id]["status"] = "completed"
                logger.info(f"[MOCK_TELEPHONY] Call {call_id} completed naturally.")
                await client.post(webhook_url, json={"event": "completed", "provider_call_id": call_id})
